# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0002_auto_20161123_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notatka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('rozpoczecie', models.DateTimeField(auto_now_add=True)),
                ('zakonczenie', models.DateTimeField()),
                ('sciezka', models.FilePathField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
                ('haslo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zadanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proman.Projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czlonek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proman.Uzytkownik')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proman.Projekt')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='task',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='projectname',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='team',
            name='member',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='zadanie',
            name='wykonawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proman.Zespol'),
        ),
        migrations.AddField(
            model_name='projekt',
            name='wlasciciel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proman.Uzytkownik'),
        ),
        migrations.AddField(
            model_name='notatka',
            name='zadanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proman.Zadanie'),
        ),
        migrations.AlterUniqueTogether(
            name='zespol',
            unique_together=set([('projekt', 'czlonek')]),
        ),
    ]
