# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0006_auto_20161129_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'wiadomości'},
        ),
        migrations.AddField(
            model_name='messages',
            name='contents',
            field=models.TextField(default=None, verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(verbose_name='treść'),
        ),
    ]
