# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proman', '0009_auto_20161130_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateTimeField(verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('project', 'member')]),
        ),
    ]
