# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0011_auto_20161130_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sender',
        ),
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateField(verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(verbose_name='Data rozpoczęcia'),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
