# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0012_auto_20161207_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'notatka', 'verbose_name_plural': 'notatki'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'zadanie', 'verbose_name_plural': 'zadania'},
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='zadanie', max_length=80, verbose_name='nazwa zadania'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nazwa projektu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contractor',
            field=models.ForeignKey(db_column='member', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='wykonawca'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proman.Project', verbose_name='nazwa projektu'),
        ),
    ]
