# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0013_auto_20161207_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='passforjoin',
            field=models.CharField(default='haselko', editable=False, max_length=80),
        ),
    ]
