# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0014_project_passforjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete_proc',
            field=models.IntegerField(default=0, verbose_name='procent wykonania projektu'),
        ),
        migrations.AddField(
            model_name='task',
            name='complete_proc',
            field=models.IntegerField(default=0, verbose_name='procent wykonania zadania'),
        ),
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='procent z całości'),
        ),
        migrations.AlterField(
            model_name='project',
            name='passforjoin',
            field=models.CharField(max_length=80),
        ),
    ]
