# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 22:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0016_auto_20161228_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complete_proc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='procent wykonania projektu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete_proc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='procent wykonania zadania'),
        ),
        migrations.AlterField(
            model_name='task',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='waga zadania'),
        ),
    ]
