# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0018_task_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 2, 12, 38, 50, 888033), verbose_name='Data utworzenia'),
        ),
    ]
