# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0019_auto_20170102_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 2, 11, 43, 51, 501401, tzinfo=utc), verbose_name='Data utworzenia'),
        ),
    ]
