# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0021_auto_20170106_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='task',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
