# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.CharField(max_length=30, verbose_name='Nadawca'),
        ),
    ]
